config/routes.rb
Rails.application.routes.draw do
  root to: "home#show"
  
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :sessions, only: [:create, :destroy]
  resource :home, only: [:show]
  resources :settings, only: [:index]
  resources :users, only: [:edit, :update]
  resources :players, only: [:new, :create, :edit, :update, :destroy]
  resources :courses, only: [:index, :show]

  get 'courses/:id/tee_times', to: 'tee_times#index', as: 'tee_times'
  get 'courses/:course_id/tee_times/:id', to: 'tee_times#show', as: 'tee_time'

  resources :orders, only: [:index, :create]
end

app/models/tee_time.rb
class TeeTime
  attr_reader :id, :unit_price, :course_id, :booked, :quantity, :time, :date, :total_price, :tee_off_at

  def initialize(tee_time_attributes)
    @id = tee_time_attributes['id']
    @tee_off_at = tee_time_attributes['tee_off_at']
    @unit_price = tee_time_attributes['unit_price']
    @course_id = tee_time_attributes['course_id']
    @booked = tee_time_attributes['booked']
    @quantity = tee_time_attributes['quantity']
  end

  def self.service
    BirdService.new
  end

  def date
    tee_off_at = @tee_off_at
    date = DateTime.parse(tee_off_at)
    formatted_date = date.strftime('%a %b %d')
  end

  def time
    time = DateTime.parse(@tee_off_at)
    formatted_time = time.strftime('%l:%M %p')
  end

  def unit_price
    convert_to_dollars(@unit_price)
  end

  def convert_to_dollars(amount)
    '%.2f' % (amount.to_i)
  end

  def total_price(tee_time)
    convert_to_dollars(tee_time.unit_price.to_i*tee_time.quantity.to_i)
  end

  def self.find_by_course(id)
    service.tee_times_by_course_id(id).map do |tee_time|
      new(tee_time)
    end.reverse
  end

  def self.find_by_course_tee_time(course_id, id)
    new(service.tee_time_by_course_id_and_tee_time_id(course_id, id))
  end

  def self.update_quantity(course_id, id, quantity)
    service.update_tee_time_quantity(course_id, id, quantity)
  end
end

app/controllers/tee_times_controller.rb
class TeeTimesController < ApplicationController
  def index
    @tee_times = TeeTime.find_by_course(params[:id])
    @course = Course.find(params[:id])
  end

  def show
    @tee_time = TeeTime.find_by_course_tee_time(params[:course_id], params[:id])
    @course = Course.find(params[:course_id])
    @players = Player.all
  end
end

app/views/tee_times/index.html.erb
<div id="tee_time_list">
  <div class="well col-md-8 col-xs-11 mobile-well">
    <div class="col-md-12 fit-width mobile-main">
      <table class="table">
        <h2><%= link_to @course.name, course_path(@course.id), style: "color: blue" %></h2>
        <%= @course.street %>
        <%= @course.location %><br>
        <%= @course.phone %>
        <thead class="table-head">
          <tr>
            <th>Time</th>
            <th>Date</th>
            <th>Available</th>
            <th>Unit Price</th>
            <th>Purchase</th>
          </tr>
        </thead>
        <tbody class="table-body">
          <% @tee_times = @tee_times.sort_by {|obj| obj.tee_off_at} %>
          <% @tee_times.each do |tee_time| %>
          <tr>
            <td><%= link_to tee_time.time, tee_time_path(tee_time.course_id, tee_time.id), style: "color: blue" %></td>
            <td class="mobile-center"><%= tee_time.date %></td>
            <td class="mobile-center"><%= tee_time.quantity %></td>
            <td>$<%= tee_time.unit_price %></td>
            <% if current_user %>
            <td class="mobile-center"><%= link_to 'Book', tee_time_path(tee_time.course_id, tee_time.id), class: 'btn btn-primary btn-sm' %></td>
            <% else %>
            <td class="mobile-center"><%= link_to "Log in with Google to View Tee Times", "/auth/google_oauth2", class: 'btn btn-primary btn-sm', id: "log_in" %></td>
            <% end %>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/tee_times/show.html.erb
<div id="tee_time_list">
  <%= form_tag("/orders") do %>
  <div class="row">
    <div class="well col-md-7 mobile-book-wells">
      <div class="table-responsive col-md-10">
        <%= hidden_field_tag(:id, @tee_time.id) %>
        <%= hidden_field_tag(:course_id, @tee_time.course_id) %>
        <table class="table">
          <h2><%= link_to @course.name, course_path(@course.id), style: "color: blue" %></h2>
          <%= @course.street %>
          <%= @course.location %><br>
          <%= @course.phone %>
          <h4 class="mobile-date"> <%= @tee_time.date %> </h4>
          <thead class="table-head">
            <tr>
              <th>Time</th>
              <th class="hide-mobile">Date</th>
              <th>Players</th>
              <th class="hide-mobile">Unit Price</th>
              <th>Total</th>
              <th>Purchase</th>
              <th></th>
            </tr>
          </thead>
          <tbody class="table-body">
            <tr>
              <td><%= @tee_time.time %></td>
              <td class="hide-mobile"><%= @tee_time.date %></td>
              <td>
                <%= select_tag(:quantity, options_for_select([4, 3, 2, 1])) %>
              </td>
              <td class="hide-mobile">$<%= @tee_time.unit_price %></td>
              <td id="total_price">$<%= @tee_time.total_price(@tee_time) %></td>
              <td><%= button_to 'Confirm', orders_path, class: 'btn btn-primary btn-sm' %></td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
    <div class="well col-md-3 mobile-book-wells">
      <div class="table-responsive col-md-12 fit-width">
        <table class="table">
          <h2>Send text</h2>
          <h4>Select players / Enter numbers</h4>
          <thead>
            <tr>
              <th>Name</th>
              <th>Phone</th>
            </tr>
          </thead>
          <tbody id="players">
            <tr>
              <td><%= current_user.name %></td>
              <td><%= current_user.formatted_phone %></td>
            </tr>
            <% player_options = @players.map { |p| [p.name, p.id] } %>
            <tr>
              <td>
                <%= select_tag(:player_1_id, options_for_select(player_options)) %>
              </td>
              <td>
                <%= @players[0].formatted_phone %>
              </td>
            </tr>
            <tr>
              <td>
                <%= select_tag(:player_2_id, options_for_select(player_options, @players[1].id)) %>
              </td>
              <td>
                <%= @players[1].formatted_phone %>
              </td>
            </tr>
            <tr>
              <td>
                <%= select_tag(:player_3_id, options_for_select(player_options, @players[2].id)) %>
              </td>
              <td>
                <%= @players[2].formatted_phone %>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
  <% end %>
</div>

<script>
$(document).ready(function () {
  $("#quantity").change(function () {
    var newTotalPrice = $("#quantity").val() * <%= @tee_time.unit_price %>
    $("#total_price").text('$'+newTotalPrice.toFixed(2))
    updatePlayers()
  });

  function updatePlayers() {
    var quantity = $("#quantity").val()
    var playerRows = $("#players > tr")
    if (quantity == 4) {
      playerRows.css("display", "")
    } else if (quantity == 3) {
      playerRows.css("display", "")
      playerRows.last().css("display", "none")
    } else if (quantity == 2) {
      playerRows.css("display", "")
      playerRows.last().prev().css("display", "none")
      playerRows.last().css("display", "none")
    } else if (quantity == 1) {
      playerRows.css("display", "none")
      playerRows.first().css("display", "")
    }
  }
});
</script>