config/routes.rb
Rails.application.routes.draw do
  root to: "home#show"
  
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :sessions, only: [:create, :destroy]
  resource :home, only: [:show]
  resources :settings, only: [:index]
  resources :users, only: [:edit, :update]
  resources :players, only: [:new, :create, :edit, :update, :destroy]
  resources :courses, only: [:index, :show]

  get 'courses/:id/tee_times', to: 'tee_times#index', as: 'tee_times'
  get 'courses/:course_id/tee_times/:id', to: 'tee_times#show', as: 'tee_time'

  resources :orders, only: [:index, :create]
end

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#hamburger" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "EarlyBird", root_path, class: "navbar-brand", style: "color: blue" %>
    </div>
    <div class="collapse navbar-collapse" id="hamburger">
      <ul class="nav navbar-nav top-margin">
        <%= link_to "Courses", courses_path, style: "color: blue" %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
        <li><%= link_to "Settings", settings_path, style: "color: blue" %></li>
        <li class="top-margin">Welcome, <%= current_user.name %></li>
        <li><%= link_to "Log out", logout_path, style: "color: blue", id: "sign_out" %></li>
        <% else %>
        <li><%= link_to "Log in with Google", "/auth/google_oauth2", style: "color: blue", id: "log_in" %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_player_form.html.erb
<div class="well col-md-3 player-form">
  <%= form_for [@user, @player] do |f| %>
  <%= f.text_field :name, placeholder: "Name" %>
  <br>
  <%= f.text_field :phone, placeholder: "Phone Number" %>
  <br>
  <%= f.submit "Submit", class: "btn btn-primary btn-sm pull-right margin-top-player" %>
  <% end %>
  <%= link_to "Cancel", settings_path, class: "btn btn-warning btn-sm pull-left margin-top-player" %>
</div>

app/views/shared/_player_form_mobile.html.erb
<div class="well col-xs-10">
  <%= form_for [@user, @player] do |f| %>
  <%= f.text_field :name, placeholder: "Name" %>
  <br><br>
  <%= f.text_field :phone, placeholder: "Phone Number" %>
  <br><br>
  <%= f.submit "Submit", class: "btn btn-primary btn-sm pull-right margin-top-player" %>
  <% end %>
  <%= link_to "Cancel", settings_path, class: "btn btn-warning btn-sm pull-left margin-top-player" %>
</div>

app/views/shared/_player_form_web.html.erb
<div class="well col-md-3 player-form">
  <%= form_for [@user, @player] do |f| %>
  <%= f.text_field :name, placeholder: "Name" %>
  <br>
  <%= f.text_field :phone, placeholder: "Phone Number" %>
  <br>
  <%= f.submit "Submit", class: "btn btn-primary btn-sm pull-right margin-top-player" %>
  <% end %>
  <%= link_to "Cancel", settings_path, class: "btn btn-warning btn-sm pull-left margin-top-player" %>
</div>