config/routes.rb
Rails.application.routes.draw do
  root to: "home#show"
  
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :sessions, only: [:create, :destroy]
  resource :home, only: [:show]
  resources :settings, only: [:index]
  resources :users, only: [:edit, :update]
  resources :players, only: [:new, :create, :edit, :update, :destroy]
  resources :courses, only: [:index, :show]

  get 'courses/:id/tee_times', to: 'tee_times#index', as: 'tee_times'
  get 'courses/:course_id/tee_times/:id', to: 'tee_times#show', as: 'tee_time'

  resources :orders, only: [:index, :create]
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  def index
    @players = Player.all
    @orders = Order.all
    @orders = Order.last(3)
  end
end

app/views/settings/index.html.erb
<div class='container-fluid'>
  <div class="row settings text-center">
<!-- web -->
    <div class="well col-md-3 col-md-offset-2 web">
      <table class="user-table">
        <h3> <%= link_to "My Number", edit_user_path(current_user), style: "color: blue" %></h3>
        <thead>
          <tr>
            <th>Name</th>
            <th>Phone</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td class="text-left"><%= current_user.name %></td>
            <td class="text-left"><%= current_user.formatted_phone %></td>
          </tr>
        </tbody>
      </table>
    </div>
<!-- mobile -->
    <div class="well mobile settings-user-info">
      <table class="user-table">
        <h3> <%= link_to "My Number", edit_user_path(current_user), style: "color: blue" %></h3>
        <thead>
          <tr>
            <th>Name</th>
            <th>Phone</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td class="text-left"><%= current_user.name %></td>
            <td class="text-left"><%= current_user.formatted_phone %></td>
          </tr>
        </tbody>
      </table>
    </div>
<!-- web -->
    <div class="well col-md-3 web test">
      <h3><%= link_to 'All Orders', orders_path, style: "color: blue" %></h3>
      <h5>Upcoming Tee Times</h5>
      <table class="settings-orders-table">
        <thead>
          <% if @orders.present? %>
          <tr class="player-tr">
            <th>Course</th>
            <th>Date</th>
            <th>Time</th>
          </tr>
          <% else %>
          <tr>
            <th>You have no orders</th>
          </tr>
          <% end %>
        </thead>
        <tbody>
          <% @orders.each do |order| %>
          <tr class="text-left">
            <td class="padding-right"><%= order.course_name %></td>
            <td class="padding-right"><%= order.date(order.tee_off_at) %></td>
            <td><%= order.time(order.tee_off_at) %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
<!-- mobile -->
    <div class="well mobile settings-user-info">
      <h3><%= link_to 'All Orders', orders_path, style: "color: blue" %></h3>
      <h5>Upcoming Tee Times</h5>
      <table class="settings-orders-table">
        <thead>
          <% if @orders.present? %>
          <tr class="player-tr">
            <th>Course</th>
            <th>Date</th>
            <th>Time</th>
          </tr>
          <% else %>
          <tr>
            <th>You have no orders</th>
          </tr>
          <% end %>
        </thead>
        <tbody>
          <% @orders.each do |order| %>
          <tr class="text-left">
            <td class="padding-right"><%= order.course_name %></td>
            <td class="padding-right"><%= order.date(order.tee_off_at) %></td>
            <td><%= order.time(order.tee_off_at) %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
<!-- web -->
    <div class="well col-md-3 web">
      <table class="player-table">
        <h3><%= link_to 'Add Player', new_player_path, style: "color: blue" %></h3>
        <thead>
          <% if @players.present? %>
          <tr class="player-tr">
            <th>Name</th>
            <th>Phone</th>
            <th>Edit</th>
            <th>Remove</th>
          </tr>
          <% end %>
        </thead>
        <tbody>
          <% @players.each do |player| %>
          <tr class="player-tr">
            <td class='text-left'><%= player.name %></td>
            <td><%= player.formatted_phone %></td>
            <td><%= link_to "Edit", edit_player_path(player), class: "btn btn-warning btn-xs" %></td>
            <td><%= button_to "Delete", player_path(player), class: "btn btn-danger btn-xs", method: :delete %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
<!-- mobile -->
    <div class="well mobile settings-user-info">
      <table class="player-table">
        <h3><%= link_to 'Add Player', new_player_path, style: "color: blue" %></h3>
        <thead>
          <% if @players.present? %>
          <tr class="player-tr">
            <th>Name</th>
            <th>Phone</th>
            <th>Edit</th>
            <th>Remove</th>
          </tr>
          <% end %>
        </thead>
        <tbody>
          <% @players.each do |player| %>
          <tr class="player-tr">
            <td class='text-left'><%= player.name %></td>
            <td><%= player.formatted_phone %></td>
            <td><%= link_to "Edit", edit_player_path(player), class: "btn btn-warning btn-xs" %></td>
            <td><%= button_to "Delete", player_path(player), class: "btn btn-danger btn-xs", method: :delete %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>