config/routes.rb
Rails.application.routes.draw do
  root to: "home#show"
  
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :sessions, only: [:create, :destroy]
  resource :home, only: [:show]
  resources :settings, only: [:index]
  resources :users, only: [:edit, :update]
  resources :players, only: [:new, :create, :edit, :update, :destroy]
  resources :courses, only: [:index, :show]

  get 'courses/:id/tee_times', to: 'tee_times#index', as: 'tee_times'
  get 'courses/:course_id/tee_times/:id', to: 'tee_times#show', as: 'tee_time'

  resources :orders, only: [:index, :create]
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def index
    @courses = Course.all
  end

  def show
    @course = Course.find(params[:id])
  end
end

app/views/courses/index.html.erb
<div class="page-content">
  <h1 class="courses"><strong>Courses</strong></h1>
  <div class="course-list">
    <% @courses.each do |course| %>
    <div class ="well col-md-3 text-center course">
      <p><%= image_tag(course.image , alt: "#{course.name} pic", class: 'img-thumbnail course-image') %></p>
      <p><%= course.name %></p>
      <p><%= course.location %></p>
      <p><%= link_to 'View Course', course_path(course.id), class: 'btn btn-primary btn-sm' %></p>
    </div>
    <% end %>
  </div>
</div>

app/views/courses/show.html.erb
<div class="page-content">
  <div class ="well col-md-4  col-xs-10 text-center course">
    <h1 class="pull-left"><strong><%= @course.name %></strong></h1><br><br><br><br>
    <main class="pull-left">
      <%= @course.street %>
      <%= @course.location %>
    </main><br>
    <main class="pull-left phone"><%= @course.phone %></main>
    <p><%= image_tag(@course.image , alt: "#{@course.name} pic", class: 'img-thumbnail course-image-show') %></p>
    <p class="web-tee-time-btn"><%= link_to "Tee Times", tee_times_path(@course.id), class: 'btn btn-primary btn-md' %></p>
    <% if current_user %>
    <p class="mobile-tee-time-btn"><%= link_to "Tee Times", tee_times_path(@course.id), class: 'btn btn-primary btn-md' %></p>
    <% else %>
    <p class="mobile-tee-time-btn"><%= link_to "Log in with Google to View Tee Times", "/auth/google_oauth2", class: 'btn btn-primary btn-md', id: "log_in" %></p>
    <% end %>
  </div>
</div>